# Homework 1: NumPy & SciPy


Homework 1 is out, it is notebook form. You need to fill in the answers in the cells and produce graphs. Everything needed for the assignment is explained in the notebook. 

**How to submit**

You need to send the `.ipynb` file with your answers plus an `.html` file, which will serve as a backup for us in case the `.ipynb` file cannot be opened on my or the TA's computer. 

The homework solution should be uploaded on e-campus. You can submit it as often as you like before the deadline.

**Important**

- Please make sure that you provide an answer in each cell and place that contains the **[ your answer ]** tags.
- The places that require your code answer are marked with `"# YOUR CODE"` comments.
- Note that you may use 1 or more line of code for replacing each `"# YOUR CODE"` comment.

## NumPy
- Most common package for scientific computing with Python
- Its fundamental object is `np.array`, an multidimensional array of numbers
- Provides linear algebra, Fourier transform, random number capabilities
- Building block for other packages (e.g. SciPy, scikit-learn)
- Open source, huge dev community!

In [ ]:
import numpy as np

## Numpy

Main object type is `np.array`

Many ways to create it,

One way is to convert a python list

In [ ]:
python_list = [ 1,2,3 ]
np.array(python_list)

In [ ]:
arr = np.array([1,2,3])
arr

Many times a list comprehension is used to create a list and then converted to a array

In [ ]:
arr = np.array([ 2**i for i in [2,3,9] ])
arr

In [ ]:
arr = np.array([ 2**i for i in range(10) if i!= 5 ])
arr

# Question 1
Create a numpy array that contain  intergers i  such that  0<i<100 and $2^i$ has the last digit 6

In [ ]:
#YOUR CODE HERE

# Question 2
Create a 2D numpy array $A$ such that $A_{ij} = i\times j$

In [ ]:
#YOUR CODE HERE

## Vectorization

In [ ]:
def fn(x):
    return x*x + 4*x +5

In [ ]:
fn(10)

In [ ]:
fn(np.linspace(0,1,10))

# Question 3
Create an array of first 10 powers of 2

In [ ]:
#YOUR CODE HERE

## Another way to create a numpy array is with initializing functions

- np.zeros
- np.ones
- np.arange

These functions along with `reshape` can be used to create initial matrix without any for loops

In [ ]:
np.zeros((10,10))

In [ ]:
5*np.ones((10,10))

In [ ]:
np.arange(2,10, 2)

You can combine these functions with arithmetic operations

In [ ]:
np.zeros((10,10)) + 5

In [ ]:
np.ones((10,10))*5

In [ ]:
np.arange(10).reshape(10,1)*np.ones((10,10))

### Distinction between numpy 1D arrays and numpy 2D arrays

This tends to cause a lot of confusion for new numpy users.
Follow the below examples carefully to understand the distinction.

In [ ]:
X = np.arange(10)
print(X)
print(X.shape)

In [ ]:
Y=np.arange(10).reshape(-1,1)
print(Y)
print(Y.shape)

In [ ]:
Z=np.arange(10).reshape(1,-1)
print(Z)
print(Z.shape)

In [ ]:
Z.squeeze()

In [ ]:
Mat = np.random.randn(10,10)

In [ ]:
Mat@X

## Array Broadcasting

Normally you only do arithmetic operations between arrays of the same dimension

In [ ]:
np.ones((5,5,5)) 

In [ ]:
np.ones((5,5,5)) + np.arange(5*5*5).reshape(5,5,5)

In [ ]:
np.ones((5,5,5)) + np.arange(5).reshape(5,1,1)

In [ ]:
np.ones((1,5,5)) + np.ones((5,1,5))

# Question 4
create a 2D numpy array $A$ such that $A_{ij} = i\times j$, but without using list comprehensions. Use broadcasting instead


In [ ]:
#YOUR CODE HERE

# Question 5
Use array broadcasting to create a (10,10) numpy array with values
$$ A_{ij} = 2^i + j $$

In [ ]:
#YOUR CODE HERE

## Matrix creation

There are some functions to create standard matrices

In [ ]:
np.eye(10)

In [ ]:
M = np.diag(np.arange(10))
M

In [ ]:
np.diag(M)

In [ ]:
A = np.arange(30).reshape(5,3,2).transpose(1,2,0)
A.shape

In [ ]:
x = np.arange(3).reshape(-1,1)
y = np.arange(3).reshape(1,-1)
np.dot(x,y)

In [ ]:
x @ y

# Question 6

Create this matrix 
```
array([[5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 4., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 5.]])```

In [ ]:
#YOUR CODE HERE

## Array Indexing and Slicing

In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr[5], arr[-2]

In [ ]:
arr[3:7]

In [ ]:
arr[:-2]

In [ ]:
arr[0:6:2]

In [ ]:
arr[5:0:-2]

In [ ]:
arr[::-1]

In [ ]:
arr[-1]

Can use all the above slicing methods for each dimension of a multidemnsional array
![](http://scipy-lectures.org/_images/numpy_indexing.png)

try it yourself

In [ ]:
a = 10*np.arange(6).reshape(-1,1)+np.arange(6)
a

In [ ]:
a[0,3:5]

# Question 7

Create the following matrix
```
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])```

In [ ]:
#YOUR CODE HERE

# Question 8 

Create the following matrix
```
array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0.,  1.,  2.,  3.,  4., -1., -1., -1., -1.],
       [-1.,  5.,  6.,  7.,  8.,  9., -1., -1., -1., -1.],
       [-1., 10., 11., 12., 13., 14., -1., -1., -1., -1.],
       [-1., 15., 16., 17., 18., 19., -1., -1., -1., -1.],
       [-1., 20., 21., 22., 23., 24., -1., -1., -1., -1.],
       [-1., 25., 26., 27., 28., 29., -1., -1., -1., -1.],
       [-1., 30., 31., 32., 33., 34., -1., -1., -1., -1.],
       [-1., 35., 36., 37., 38., 39., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]])```

In [ ]:
#YOUR CODE HERE

# Fancy Array Indexing

We can use numpy arrays as an index for other numpy arrays

In [ ]:
arr = np.arange(10)
arr

In [ ]:
idx = np.array([7,-5,2])

In [ ]:
arr[idx]=-1
arr

In [ ]:
arr<0

In [ ]:
arr[arr<0] = np.arange(3)
arr

For multidimensional array, array indexing works different from slicing

In [ ]:
X = np.zeros((10,10))
X[3:8,3:9]=1
X

In [ ]:
X = np.zeros((10,10))
X[np.arange(3,9),np.arange(3,9)]=1
X

![](http://scipy-lectures.org/_images/numpy_fancy_indexing.png)

# Question 9 

Create the following matrix
```
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])```

In [ ]:
#YOUR CODE HERE

We can use `np.where`, to get indices of the `True` values in a boolean array

In [ ]:
np.where(X>0)

In [ ]:
#X = np.arange(10)
Y = np.zeros((10,10))
Y[np.where(X>0)]=2
Y

## Reduction operations

Many reduction functions are available

- np.sum, np.prod
- np.min, np.max
- np.any, np.all

Partial reductions

- np.cumsum, np.cumprod

In [ ]:
X = np.arange(100).reshape(10,10)
X

In [ ]:
np.sum(X),np.prod(X)

In [ ]:
np.prod(X,axis=1)

In [ ]:
np.min(X),np.max(X)

In [ ]:
np.min(X,axis=0)

In [ ]:
Y = X<1
Y

In [ ]:
np.any(Y)

In [ ]:
np.all(Y)

All the above functions can be called on the array object directly

In [ ]:
X.max(axis=0)

In [ ]:
(np.sqrt(X*X*X)<5000).all()

In [ ]:
np.cumsum(np.ones((10,10)),axis=1)

Cumulative operations don't change the shape of the array

In [ ]:
np.cumsum(X,axis=0)

# Question 10

- Given X matrix below, 
- Find the column with maximum column sum
- For which rows of the matrix, the sum of the first three elements of the row is greater than the sum of the last two elements of the row. We can use `np.where`.

In [ ]:
np.random.seed(10)
X = np.random.rand(5,5)
X

In [ ]:
#YOUR CODE HERE

## SciPy
Scipy is a collection of packages that provide useful mathematical functions commonly used for scientific computing.

List of subpackages
- cluster : Clustering algorithms
- constants : Physical and mathematical constants
- fftpack : Fast Fourier Transform routines
- integrate : Integration and ordinary differential equation solvers
- interpolate : Interpolation and smoothing splines
- io : Input and Output
- linalg : Linear algebra
- ndimage : N-dimensional image processing
- odr : Orthogonal distance regression
- optimize : Optimization and root-finding routines
- signal : Signal processing
- sparse : Sparse matrices and associated routines
- spatial : Spatial data structures and algorithms
- special : Special functions
- stats : Statistical distributions and functions

## Interpolation : `scipy.interpolate`

In [ ]:
import scipy.interpolate as interp
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(-1,2,5);
y = x**3
plt.plot(x,y,'bo')

# Question 11

Create a cubic interpolation function 

In [ ]:
#YOUR CODE HERE
# f=

In [ ]:
# new x points are given as:
xnew = np.linspace(-1,2,100)

Apply your interpolation function to find the value of new points 

In [ ]:
#YOUR CODE HERE

Plot (x,y) and (xnew,ynew) using `plt.plot` and `plt.show`.

In [ ]:
#YOUR CODE HERE

## Numerical Integration : `scipy.integrate`

In [ ]:
import scipy.integrate as integ

Function is given as:

In [ ]:
def f(x):
    return x**2 + 5*x + np.sin(x)

# Question 12

Compute a definite integral from -1 to 1

In [ ]:
#YOUR CODE HERE